global:
  scrape_interval: 15s # How often to scrape targets by default.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Prometheus itself

  # follow this setup: https://docs.docker.com/engine/daemon/prometheus/
  - job_name:
      docker
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
    static_configs:
      - targets: ["host.docker.internal:9323"]
