global:
  scrape_interval: 15s # How often to scrape targets by default.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Prometheus itself

  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"] # Docker exporter metrics
