name: Homelab Deployment

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify the version you need

      - name: Configure Terraform Cloud credentials
        run: |
          echo "TFC_TOKEN=${{ secrets.TF_TOKEN }}" > ~/.terraform.d/credentials.tfrc.json

      - name: Set SSH Private Key as Environment Variable
        run: echo "ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
# name: Homelab Deployment

# on:
#   workflow_dispatch:

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup SSH
#         uses: appleboy/ssh-action@v0.1.10
#         with:
#           host: "173.206.63.235"
#           username: "patrick"
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: "2222"
#           command_timeout: 2m
#           script: |
#             terraform init
#             # Run Terraform plan and apply
#             terraform plan
#             terraform apply -auto-approve

