name: Homelab Deployment

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Read script contents
      #   id: script
      #   uses: andstor/file-reader-action@v1
      #   with:
      #     path: scripts/deploy.sh

      - name: Copy Terraform files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "173.206.63.235"
          username: "patrick"
          port: "2222"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "main.tf"
          target: "/home/patrick"

      - name: Setup SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "173.206.63.235"
          username: "patrick"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: "2222"
          command_timeout: 30m
          script: |
            export TF_TOKEN_app_terraform_io=${{secrets.TF_TOKEN}}
            terraform init
            terraform apply -auto-approve
