name: Homelab Deployment

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH Private Key File
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_private_key
          chmod 600 /tmp/ssh_private_key

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify the version you need

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
# name: Homelab Deployment

# on:
#   workflow_dispatch:

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup SSH
#         uses: appleboy/ssh-action@v0.1.10
#         with:
#           host: "173.206.63.235"
#           username: "patrick"
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: "2222"
#           command_timeout: 2m
#           script: |
#             terraform init
#             # Run Terraform plan and apply
#             terraform plan
#             terraform apply -auto-approve

