name: Homelab Deployment

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "173.206.63.235"
          username: "patrick"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: "2222"
          command_timeout: 2m
          script: |
            git clone https://github.com/patrickl13/homelab.git
            cd homelab
            terraform init
            terraform apply -auto-approve
