name: SSH into Raspberry Pi

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Clear known_hosts for Raspberry Pi
        run: |
          ssh-keygen -R 173.206.63.235

      - name: Add Raspberry Pi to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 173.206.63.235 >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 644 ~/.ssh/known_hosts

      - name: Test SSH connection to Raspberry Pi
        run: |
          ssh -i ~/.ssh/id_rsa patrick@173.206.63.235 -p 2222 "echo 'Connection successful!'"
